export const kipuConfig = {
  feedback: {
    style: {
      top: '50%',
      left: '50%',
      position: 'fixed',
      transform: 'translate(-50%, -50%)',
    },
  },
  supervision: {
    style_component: '#e-supervision-button {color: black;}',
    main_screen_selector: 'div#container div#main-area',
    menu_element_selector: 'div#container #navigation ul',
    button_to_clone_selector: 'div#container #navigation ul li:not(.active)',
  },
  feature_flags: {
    use_note_discrepancy: true,
  },
  progress_note: {
    page_id: 'Progress Note-',
    report_fields: {
      data: '.patient_evaluation_item:has(div:contains("Data")):has(textarea):contains()',
      mood: '.patient_evaluation_item:has(div:contains("Mood")):contains()',
      plan: '.patient_evaluation_item:has(div:contains("Plan")):has(textarea):contains()',
      affect: '.patient_evaluation_item:has(div:contains("Affect")):contains()',
      speech: '.patient_evaluation_item:has(div:contains("Speech")):contains()',
      posture: '.patient_evaluation_item:has(div:contains("Posture")):contains()',
      attitude: '.patient_evaluation_item:has(div:contains("Attitude")):contains()',
      behavior: '.patient_evaluation_item:has(div:contains("Behavior")):contains()',
      hide_plan: '.patient_evaluation_item:has(div:contains("Plan")):has(textarea):contains():first',
      appearance: '.patient_evaluation_item:has(div:contains("Appearance")):contains()',
      assessment: '.patient_evaluation_item:has(div:contains("Assessment")):has(textarea):contains()',
      oriented_to: '.patient_evaluation_item:has(div:contains("Oriented To:")):contains()',
      client_review: '.patient_evaluation_item:has(div:contains("Client Review/Consultation in Staffing")):contains()',
      aftercare_plan: '.patient_evaluation_item:has(div:contains("Aftercare Plan:")):contains()',
      hours_of_sleep: '.patient_evaluation_item:has(div:contains("Hours of Sleep per Night")):contains()',
      sleep_problems: '.patient_evaluation_item:has(div:contains("Sleep Problems?")):contains()',
      recommended_loc: '.patient_evaluation_item:has(div:contains("Recommended LOC:")):contains()',
      stage_of_change: '.patient_evaluation_item:has(div:contains("Stage of Change:")):contains()',
      thought_content: '.patient_evaluation_item:has(div:contains("Thought Content")):contains()',
      thought_process: '.patient_evaluation_item:has(div:contains("Thought Process")):contains()',
      current_symptoms: '.patient_evaluation_item:has(div:contains("Current Symptoms")):contains()',
      posture_comments: '._20:has(label:contains("Comments")):contains()',
      doc_craving_scale: '.patient_evaluation_item:has(div:contains("DOC Craving Scale")):contains()',
      suicidal_homicidal: '.patient_evaluation_item:has(div:contains("Suicidal/Homicidal")):contains()',
      motivation_for_change: '.patient_evaluation_item:has(div:contains("Motivation for Change")):contains()',
      current_distress_level: '.patient_evaluation_item:has(div:contains("Current Distress Level")):contains()',
      thought_content_comment: '._20:has(label:contains("Other:")):contains()',
      barriers_to_step_down_text: '.patient_evaluation_item:has(div:contains("Barriers to Step-Down or Discharge & Reccomendations:")):contains()',
      hide_mental_status_exam_header: '.patient_evaluation_item:has(div:contains("Mental Status Exam")):contains()',
      any_issues_activities_daily_living: '.patient_evaluation_item:has(div:contains("Any issues with Activities of Daily Living?")):contains()',
      any_issues_activities_daily_living_describe_issues: '.patient_evaluation_item:has(div:contains("Describe Issues:")):contains()',
    },
    submit_button: '.btn.btn-primary:has(span:contains("Sign & Submit")):contains()',
    is_note_signed: 'div.wrap:has(img[alt="signature"])',
    parent_selector: '.patient_evaluation_item:has(div:contains("Golden Thread")):contains()',
    form_note_selector: 'form[action*=patient_evaluations]',
  },
  progress_notes: [
    {
      type: '',
      context: 'div#sub_nav_content div#evaluation:contains(Progress Note-), div#sub_nav_content div#evaluation:contains(DAP Note for Secondary Therapy)',
      category: 'notes',
      report_fields: {
        data: '.patient_evaluation_item:has(div:contains("Data")):has(textarea):contains()',
        mood: '.patient_evaluation_item:has(div:contains("Mood")):contains()',
        plan: '.patient_evaluation_item:has(div:contains("Plan")):has(textarea):contains()',
        affect: '.patient_evaluation_item:has(div:contains("Affect")):contains()',
        speech: '.patient_evaluation_item:has(div:contains("Speech")):contains()',
        posture: '.patient_evaluation_item:has(div:contains("Posture")):contains()',
        attitude: '.patient_evaluation_item:has(div:contains("Attitude")):contains()',
        behavior: '.patient_evaluation_item:has(div:contains("Behavior")):contains()',
        hide_plan: '.patient_evaluation_item:has(div:contains("Plan")):has(textarea):contains():first',
        appearance: '.patient_evaluation_item:has(div:contains("Appearance")):contains()',
        assessment: '.patient_evaluation_item:has(div:contains("Assessment")):has(textarea):contains()',
        oriented_to: '.patient_evaluation_item:has(div:contains("Oriented To:")):contains()',
        client_review: '.patient_evaluation_item:has(div:contains("Client Review/Consultation in Staffing")):contains()',
        aftercare_plan: '.patient_evaluation_item:has(div:contains("Aftercare Plan:")):contains()',
        hours_of_sleep: '.patient_evaluation_item:has(div:contains("Hours of Sleep per Night")):contains()',
        sleep_problems: '.patient_evaluation_item:has(div:contains("Sleep Problems?")):contains()',
        recommended_loc: '.patient_evaluation_item:has(div:contains("Recommended LOC:")):contains()',
        stage_of_change: '.patient_evaluation_item:has(div:contains("Stage of Change:")):contains()',
        thought_content: '.patient_evaluation_item:has(div:contains("Thought Content")):contains()',
        thought_process: '.patient_evaluation_item:has(div:contains("Thought Process")):contains()',
        current_symptoms: '.patient_evaluation_item:has(div:contains("Current Symptoms")):contains()',
        posture_comments: '._20:has(label:contains("Comments")):contains()',
        doc_craving_scale: '.patient_evaluation_item:has(div:contains("DOC Craving Scale")):contains()',
        suicidal_homicidal: '.patient_evaluation_item:has(div:contains("Suicidal/Homicidal")):contains()',
        motivation_for_change: '.patient_evaluation_item:has(div:contains("Motivation for Change")):contains()',
        current_distress_level: '.patient_evaluation_item:has(div:contains("Current Distress Level")):contains()',
        thought_content_comment: '._20:has(label:contains("Other:")):contains()',
        barriers_to_step_down_text: '.patient_evaluation_item:has(div:contains("Barriers to Step-Down or Discharge & Reccomendations:")):contains()',
        hide_mental_status_exam_header: '.patient_evaluation_item:has(div:contains("Mental Status Exam")):contains()',
        any_issues_activities_daily_living: '.patient_evaluation_item:has(div:contains("Any issues with Activities of Daily Living?")):contains()',
        any_issues_activities_daily_living_describe_issues: '.patient_evaluation_item:has(div:contains("Describe Issues:")):contains()',
      },
      submit_button: '.btn.btn-primary:has(span:contains("Sign & Submit")):contains()',
      is_note_signed: 'div.wrap:has(img[alt="signature"])',
      parent_selector: '.patient_evaluation_item:has(div:contains("Golden Thread")):contains()',
      form_note_selector: 'form[action*=patient_evaluations]',
    },
    {
      type: 'ApnKetamineDapReport',
      context: 'div#sub_nav_content div#evaluation:contains(DAP Note for Ketamine Treatment)',
      category: 'notes',
      report_fields: {
        data: '.patient_evaluation_item:has(div:contains("Data")):has(textarea):contains()',
        plan: '.patient_evaluation_item:has(div:contains("Plan")):has(textarea):contains()',
        assessment: '.patient_evaluation_item:has(div:contains("Assessment")):has(textarea):contains()',
      },
      submit_button: '.btn.btn-primary:has(span:contains("Sign & Submit")):contains()',
      is_note_signed: 'div.wrap:has(img[alt="signature"])',
      parent_selector: '.patient_evaluation_item:has(div:contains("Golden Thread")):contains()',
      form_note_selector: 'form[action*=patient_evaluations]',
    },
    {
      type: 'ApnKetamineTreatmentReport',
      context: 'div#sub_nav_content div#evaluation:contains(Ketamine Note)',
      category: 'notes',
      report_fields: {
        progress_note: '.patient_evaluation_item:has(div:contains("Any Additional Findings")):has(textarea):contains()',
      },
      submit_button: '.btn.btn-primary:has(span:contains("Sign & Submit")):contains()',
      is_note_signed: 'div.wrap:has(img[alt="signature"])',
      parent_selector: '.form_wrap:has(.patient_evaluation_item)',
      form_note_selector: 'form[action*=patient_evaluations]',
    },
  ],
  session_analytics: {
    parent_selector: 'div.flash-messages',
  },
};
